[build]
# Use all available CPU cores for compilation
jobs = 16

[target.'cfg(all())']
# Enable native CPU optimizations and SIMD instructions
# Note: These flags work on most x86_64 systems. Remove specific features if compilation fails.
rustflags = [
    "-C", "target-cpu=native",
    "-C", "opt-level=3",
    "-C", "inline-threshold=275",
]

# Platform-specific optimizations
# Comment out sections that cause issues on your platform

# Linux with LLD linker (faster linking)
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "link-arg=-Wl,--threads=8",
    "-C", "target-feature=+avx2,+fma,+aes",
]

# macOS x86_64
[target.x86_64-apple-darwin]
rustflags = [
    "-C", "target-feature=+avx2,+fma,+aes",
]

# macOS ARM64 (Apple Silicon)
[target.aarch64-apple-darwin]
# ARM-specific optimizations
rustflags = [
    "-C", "target-feature=+neon",
] 
